name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  ci-pipeline:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      # --- Checkout the repo ---
      - name: Checkout repository
        uses: actions/checkout@v6

      # --- Setup Python environment ---
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # --- Install uv ---
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      # --- Install dependencies ---
      - name: UV sync
        run: |
          uv sync --frozen --no-cache

      # --- Run Linters ---
      - name: Ruff Linters
        run: |
          uv run ruff check .
          uv run ruff format

      # --- Unit Tests ---
      - name: Run unit tests (pytest)
        run: |
          uv add pytest
          pytest -v || echo "No tests directory or tests found"